name: Ansible Playbook on Docker Containers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker-Compose & Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose ansible

      - name: Start Docker Containers
        run: |
          docker-compose up -d

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory_github_action.yml ansible/config_kuber.yml

      - name: Tear Down Docker Containers
        if: always()
        run: docker-compose down